### ISSUE TITLE
Error: No liquidity box found for token TokenId("0000000000000000000000000000000000000000000000000000000000000000")

### ISSUE THREAD

**Issue by marctheshark3** [Telefragged/off-the-grid#136]
When trying to run: grid create -t ERG -o 10 -r 1.15-1.5 -i Erg -n 5

i got the error of no liquidity box found, not sure what that means per say. I have 18ergs in the node wallet. I have even tried the comet example with the same error. 

What am I missing here?

**Comment by Telefragged** [comment]
The reason you're seeing the error in the title is because a suitable liquidity pool is searched for using the _other_ token-id. The `token-id` parameter should be used with the token that you are trading ERG against.

As for the case when you specified comet it could either be that you misspelled the token name as it is case sensitive. The correct name is COMET. Alternatively, if you have configured the node scans using the `scans create-config` command, it could be that there hadn't been activity for the COMET pool between then and when you ran the command. This is an implementation detail of the node scans themselves which causes them to only see updates that happened after they were first created.
It is possible to trigger a rescan by using the `-r` option for `scans create-config` but this may take a while. IIRC existing scan data will also be cleared so the safest way to do this is to pass `-r 0` to trigger a full rescan.

Let me know if you have any more questions. I will also add some hints to the output in these cases shortly so this is more clear.

**Comment by marctheshark3** [comment]
Understood that makes sense why it wasnt working for ERGO. I was able to run the rescan at a very early height and was able to try to submit a transaction. though I am gettting an error with "invalid input"

![image](https://github.com/Telefragged/off-the-grid/assets/35350738/8897b4da-96bb-4d13-a269-2df355bf8a67)

Any ideas here?


Appreciate the help!!

**Comment by marctheshark3** [comment]
maybe I am not putting in the right amount for some of the inputs?

**Comment by marctheshark3** [comment]
OH duh lol

Thanks! just submitted the TX :)

**Comment by Telefragged** [comment]
Closing this issue now but if you encounter any other issues feel free to open a new one
